### ISSUE TITLE
做为使用者，提几个建议

### ISSUE THREAD

**Issue by zhengweiqing** [Suwmlee/ikaros#32]
之前一直使用 Movie_Data_Capture 奈何昨天不知道为什么突然出错了，所以改用你写的 ikaros，使用后感觉有界面还是会方便，根据日常使用有几个问题：
1 能否增加登录用户名密码，以方便外网访问。
2 能否自定义 水印 的颜色？习惯 Movie_Data_Capture 风格的标签了，颜色突然更换有点不太适应
3 移动方式刮削完成后能否自动删除源文件夹？很多av下载后，文件夹里除了视频文件还有好多推广用的视频跟图片等文件，最好能设置一个选项，在文件夹小于指定大小（例如100mb）时自动删除
4 能否自定义后缀？Movie_Data_Capture  例如原版对于 -UC 的后缀不识别，还有就是下载的av分多集的时候，后缀是_1 _2 如何识别？
5 部分av文件名前边会有3位数字，导致无法识别，最好能解决下
6 FC2PPV系列，以FC2PPV开头时，会无法识别，将文件名修改成 FC2- 后就可以正常识别，如何解决？
7 如何自动刮削？是监控文件夹变化吗？
8 能否做一个刮削目录名称的变量，例如，刮削完成后，是否可以移动到 /media/2023-09/#整理完成？

综上所述，建议能否增加一个文件名处理的规则，可以自定义添加多个规则，可以用替换法检测开头指定位数字符或者结尾字符等方式进行替换，或者正则实现。

标签样式参考下原版
![image](https://github.com/Suwmlee/ikaros/assets/50610421/73661846-6166-4f28-8993-625d6ff25f1b)

![image](https://github.com/Suwmlee/ikaros/assets/50610421/516482c4-39fd-4605-a881-1f60572f5b76)

**Comment by Suwmlee** [comment]
:smile:
> 2 能否自定义 水印 的颜色？习惯 Movie_Data_Capture 风格的标签了，颜色突然更换有点不太适应

位置可以自定义，只是图标不同的话，可以手动替换下，在 `src/images` 目录
> 4 能否自定义后缀？Movie_Data_Capture 例如原版对于 -UC 的后缀不识别，还有就是下载的av分多集的时候，后缀是_1 _2 如何识别？
> 5 部分av文件名前边会有3位数字，导致无法识别，最好能解决下
> 6 FC2PPV系列，以FC2PPV开头时，会无法识别，将文件名修改成 FC2- 后就可以正常识别，如何解决？

不需要更改文件名，刮削后查看识别不正确，可以在刮削列表内修改，点击 `🖊`，可以指定番号，指定地址，指定分集，可以自定义`中文`、`流出`等标签，更改后，点击旁边的刷新按钮即可
> 7 如何自动刮削？是监控文件夹变化吗？

目前是transmission qbittorent下载完成后触发脚本

增加用户，监控文件夹，自定义规则等可以考虑加入

**Comment by zhengweiqing** [comment]
自动删除文件夹这个功能是不是也要考虑上呢？不然如果采用移动方式的时候，会有N个空的或者只有宣传推广文件的文件夹

**Comment by zhengweiqing** [comment]
/media/GMEM-101/manko.fun.mp4 
刚刚就遇到这个问题，下载的av里还有推广视频，但是 ikaros 一样尝试进行刮削了。应该修改一下逻辑为刮削前先删除视频文件夹内小于指定大小的文件（例如50mb），然后再进行刮削，并且在刮削结束后删除空的文件夹.

并且刮削完成后，GMEM-101 这个文件夹依然存在，还要手动删除才行。

并且还有failed 刮削失败的文件是空的，但还存在，还需要手动删除才行。

![image](https://github.com/Suwmlee/ikaros/assets/50610421/a071fb78-dc0a-43dd-88b0-6829ddfb7cb6)
![image](https://github.com/Suwmlee/ikaros/assets/50610421/7ce060ba-9cb0-4ba6-a9d0-2f49d14ccffc)

**Comment by zhengweiqing** [comment]
两个问题：
1 出现了错误
2 下载图片失败了，我的科学上网是正常的，浏览器里可以正常访问图片，但是刮削下载失败了

[2023-10-10 19:54:51,936] INFO in manager: [*]======================================================
[2023-10-10 19:54:51,936] INFO in manager: [+]Find  2  movies
[2023-10-10 19:54:51,945] INFO in manager: [!]Making Data for [/media/GMEM-101/GMEM-101.H265.mp4], the number is [GMEM-101]
[2023-10-10 19:55:00,113] INFO in scraper: [+]Wrote!            /media/#整理完成/GMEM-101/GMEM-101.nfo
[2023-10-10 19:55:00,122] INFO in manager: [*]======================================================
[2023-10-10 19:55:00,135] INFO in manager: [!]Making Data for [/media/GMEM-101/manko.fun.mp4], the number is [manko', 'fun]
[2023-10-10 19:55:47,835] ERROR in scraper: [-]Movie Data not found!
[2023-10-10 19:55:47,835] INFO in scraper: [-]Move to Failed folder
[2023-10-10 19:55:47,844] INFO in manager: [*]======================================================
[2023-10-10 19:55:47,852] INFO in manager: [+] All scraping finished!!!
[2023-10-10 19:55:47,852] INFO in manager: [*]======================================================
[2023-10-10 20:00:26,421] ERROR in __init__: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/controller/scrapingctrl.py", line 78, in deleteScrapingRecordIds
    delrecords = scrapingrecordService.deleteByIds(ids, delsrc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/service/recordservice.py", line 62, in deleteByIds
    self.deleteRecord(record, delsrc)
  File "/app/src/service/recordservice.py", line 49, in deleteRecord
    folder = os.path.dirname(record.destpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType

[2023-10-10 20:00:51,287] INFO in filehelper: clean file [/media/GMEM-101/manko.fun.mp4]
[2023-10-10 20:00:51,289] ERROR in __init__: Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/controller/scrapingctrl.py", line 78, in deleteScrapingRecordIds
    delrecords = scrapingrecordService.deleteByIds(ids, delsrc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/service/recordservice.py", line 62, in deleteByIds
    self.deleteRecord(record, delsrc)
  File "/app/src/service/recordservice.py", line 49, in deleteRecord
    folder = os.path.dirname(record.destpath)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 152, in dirname
TypeError: expected str, bytes or os.PathLike object, not NoneType

[2023-10-10 20:07:55,154] INFO in manager: [*]======================================================
[2023-10-10 20:07:55,154] INFO in manager: [+]Find  0  movies
[2023-10-10 20:07:55,160] INFO in manager: [+] All scraping finished!!!
[2023-10-10 20:07:55,161] INFO in manager: [*]======================================================
[2023-10-10 20:14:39,315] INFO in manager: [*]======================================================
[2023-10-10 20:14:39,315] INFO in manager: [+]Find  1  movies
[2023-10-10 20:14:39,322] INFO in manager: [!]Making Data for [/media/HTMS-127.mp4], the number is [HTMS-127]
[2023-10-10 20:14:57,668] ERROR in scraper: [-] download failed! https://pics.dmm.co.jp/mono/movie/adult/htms127so/htms127sopl.jpg
[2023-10-10 20:14:57,668] INFO in scraper: [+]Download Cover Failed! HTMS-127-fanart.jpg
[2023-10-10 20:14:57,668] INFO in scraper: [-]Move to Failed folder
[2023-10-10 20:14:57,670] INFO in scraper: [-]Cover cut failed!
[2023-10-10 20:14:57,671] INFO in scraper: [+]Wrote!            /media/#整理完成/HTMS-127/HTMS-127.nfo
[2023-10-10 20:14:57,679] INFO in manager: [*]======================================================
[2023-10-10 20:14:57,685] INFO in manager: [+] All scraping finished!!!
[2023-10-10 20:14:57,685] INFO in manager: [*]======================================================
[2023-10-10 20:17:48,934] INFO in manager: [+]Single start!!!
[2023-10-10 20:17:48,940] INFO in filehelper: clean folder by filter [/media/#整理完成/HTMS-127/HTMS-127.nfo]
[2023-10-10 20:17:48,943] INFO in manager: [!]Making Data for [/media/HTMS-127.mp4], the number is [HTMS-127]
[2023-10-10 20:18:05,902] ERROR in scraper: [-] download failed! https://pics.dmm.co.jp/mono/movie/adult/htms127so/htms127sopl.jpg
[2023-10-10 20:18:05,902] INFO in scraper: [+]Download Cover Failed! HTMS-127-fanart.jpg
[2023-10-10 20:18:05,902] INFO in scraper: [-]Move to Failed folder
[2023-10-10 20:18:05,904] INFO in scraper: [-]Cover cut failed!
[2023-10-10 20:18:05,904] INFO in scraper: [+]Wrote!            /media/#整理完成/HTMS-127/HTMS-127.nfo
[2023-10-10 20:18:05,915] INFO in manager: [*]======================================================
[2023-10-10 20:18:05,922] INFO in manager: [+]Single finished!!!

**Comment by Suwmlee** [comment]
扫描库时，除了成功与忽略标记的记录都会再次刮削。

我们的使用场景可能不太一样。我主要是PT下载，基本不会动下载目录，除非emby库里删除了，会把种子文件一并删除。失败文件夹保留没什么问题，使用emby这些不会看到。看片就好，不用管文件夹多了几个

**Comment by zhengweiqing** [comment]
我的pt下载是在用nastool做刮削， 用这个主要是做AV的刮削，真心希望能重视一下我反馈的问题，尤其是错误日志如何解决

**Comment by zhengweiqing** [comment]
我的代理没问题，我是在群晖上搭建的clash做的代理，我的电脑也是用的群晖上的这个代理。应该不是代理的问题。

**Comment by Suwmlee** [comment]
问题已经定位，下版本修复
