### ISSUE TITLE
使用docker后容器可以启动，但是无法访问，感觉是没有关联前端，但是按照文档已经添加了web目录

### ISSUE THREAD

**Issue by lightpurple83212** [Suwmlee/ikaros#41]
/app/src/utils/filehelper.py:273: SyntaxWarning: invalid escape sequence '\('
for n in re.findall('[\(\[\（](.*?)[\)\]\）]', base):
/app/src/utils/filehelper.py:275: SyntaxWarning: invalid escape sequence '\('
cop = re.compile("[\(\[\（]" + n + "[\)\]\）]")
/app/src/utils/filehelper.py:275: SyntaxWarning: invalid escape sequence '\)'
cop = re.compile("[\(\[\（]" + n + "[\)\]\）]")
/app/src/utils/regex.py:25: SyntaxWarning: invalid escape sequence '\['
result = single.lstrip('第.EPep\[ ')
/app/src/utils/regex.py:50: SyntaxWarning: invalid escape sequence '\d'
regx = "(?:s|season)(\d{2})"
/app/src/utils/regex.py:113: SyntaxWarning: invalid escape sequence '\d'
"第\d*[話话集]",
/app/src/utils/regex.py:114: SyntaxWarning: invalid escape sequence '\('
"[ ]ep?[0-9.\(videoa\)]*[ ]",
/app/src/utils/regex.py:115: SyntaxWarning: invalid escape sequence '\.'
"\.ep?[0-9\(videoa\)]*\.",
/app/src/utils/regex.py:116: SyntaxWarning: invalid escape sequence '\.'
"\.\d{2,3}(?:v\d)?[\(videoa\)]*\.",
/app/src/utils/regex.py:117: SyntaxWarning: invalid escape sequence '\d'
"[ ]\d{2,3}(?:\.\d|v\d)?[\(videoa\)]*[ ]",
/app/src/utils/regex.py:118: SyntaxWarning: invalid escape sequence '\['
"\[(?:e|ep)?[0-9.v]*(?:\(oa\)|\(video\))?\]",
/app/src/utils/regex.py:128: SyntaxWarning: invalid escape sequence '\d'
regstr = "s(\d{1,2})ep?(\d{1,4})"
/app/src/utils/regex.py:155: SyntaxWarning: invalid escape sequence '\d'
regstr = "^(\d{1,3}) ?(_|-|.)? ?([^\W\d]+)"
/app/src/controller/optionctrl.py:73: SyntaxWarning: invalid escape sequence '\ '

install_matches = regexMatch(out, "INSTALLED:\ ([\d.]+)")
/app/src/controller/optionctrl.py:74: SyntaxWarning: invalid escape sequence '\ '

latest_matches = regexMatch(out, "LATEST:[\ ]+([\d.]+)")
/app/src/model/config.py:44: SyntaxWarning: invalid escape sequence '\('
escape_literals = Column(String, default="\()/")
/app/src/bizlogic/scraper.py:630: SyntaxWarning: invalid escape sequence '\('
ext = re.sub('\(.*?\)', '', s)
/app/src/utils/number_parser.py:6: SyntaxWarning: invalid escape sequence '\w'
"^\w+\.(cc|com|net|me|club|jp|tv|xyz|biz|wiki|info|tw|us|de)@|^22-sht\.me|"
/app/src/utils/number_parser.py:80: SyntaxWarning: invalid escape sequence '\d'
prog = re.compile("(?:-|_)cd\d{1,2}", re.IGNORECASE | re.X | re.S)
/app/src/utils/number_parser.py:85: SyntaxWarning: invalid escape sequence '\d'
prog = re.compile("(?:-|_)\d{1,2}$", re.IGNORECASE | re.X | re.S)
/app/src/utils/number_parser.py:122: SyntaxWarning: invalid escape sequence '\['
filename = re.sub("\[.*?\]","",filename)
/app/src/utils/number_parser.py:128: SyntaxWarning: invalid escape sequence '\['
filename = str(re.sub("\[\d{4}-\d{1,2}-\d{1,2}\] - ", "", filename)) # 去除文件名中时间
/app/src/utils/number_parser.py:129: SyntaxWarning: invalid escape sequence '\d'
filename = re.sub("[-_]cd\d{1,2}", "", filename, flags=re.IGNORECASE)
/app/src/utils/number_parser.py:139: SyntaxWarning: invalid escape sequence '\d'
if re.search("\d+ch$", file_number, flags=re.I):
/app/src/bizlogic/transfer.py:347: SyntaxWarning: invalid escape sequence '\d'
tempmid = replaceRegex(tempmid, '^s(\d{2})-s(\d{2})')
[2024-01-02 12:58:43,622] INFO in __init__: Initialization: upgrade db
Traceback (most recent call last):
File "/usr/local/bin/flask", line 8, in <module>
sys.exit(main())
^^^^^^
File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 1064, in main
cli.main()
File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1078, in main
rv = self.invoke(ctx)
^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
return ctx.invoke(self.callback, **ctx.params)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/click/decorators.py", line 92, in new_func
return ctx.invoke(f, obj, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
return __callback(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 912, in run_command
raise e from None
File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 898, in run_command
app = info.load_app()
^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 309, in load_app
app = locate_app(import_name, name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/flask/cli.py", line 219, in locate_app
__import__(module_name)
File "/app/app.py", line 4, in <module>
application = create_app()
^^^^^^^^^^^^
File "/app/src/__init__.py", line 58, in create_app
schedulerService.start()
File "/app/src/service/schedulerservice.py", line 22, in start
self.scheduler.start()
File "/usr/local/lib/python3.12/site-packages/flask_apscheduler/scheduler.py", line 103, in start
self._scheduler.start(paused=paused)
File "/usr/local/lib/python3.12/site-packages/apscheduler/schedulers/background.py", line 38, in start
self._thread.start()
File "/usr/local/lib/python3.12/threading.py", line 971, in start
_start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by Suwmlee** [comment]
suwmlee/ikaros:latest

docker版本已经配置好，不需要额外配置
